# Generated by Django 4.2.6 on 2023-12-13 11:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock_quote', '0003_rename_stock_stocks'),
        ('userside', '0006_stocks_delete_stockbuy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='cash_balance',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stock_symbol',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='stock',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000),
        ),
        migrations.AddField(
            model_name='stock',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='total',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AddField(
            model_name='stock',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocksell',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='transaction',
            name='symbol',
            field=models.CharField(default='no', max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='stocksell',
            name='shares',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='stocksell',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_quote.stocks'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.FloatField(default=10000.0),
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
