# Generated by Django 4.2.6 on 2023-12-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0007_remove_portfolio_cash_balance_remove_stock_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=255),
        ),
    ]
