# Generated by Django 4.2.6 on 2023-12-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0010_transaction_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=20500, max_digits=10),
        ),
    ]
