# Generated by Django 4.2.6 on 2023-12-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0012_remove_userprofile_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='balance',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='shares',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='symbol',
            field=models.CharField(default='no', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
