# Generated by Django 4.2.6 on 2023-12-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0013_remove_portfolio_balance_portfolio_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocksell',
            name='shares',
            field=models.IntegerField(),
        ),
    ]
