# Generated by Django 4.2.6 on 2023-12-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0014_alter_portfolio_shares_alter_stocksell_shares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=20500, max_digits=10),
        ),
    ]
