# Generated by Django 4.2.6 on 2023-11-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_quote', '0002_alter_stock_symbol'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Stocks',
        ),
    ]
