# Generated by Django 4.2.6 on 2023-12-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_quote', '0003_rename_stock_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='available_shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocks',
            name='name',
            field=models.CharField(default='no', max_length=100),
        ),
    ]
